GEEQUEL-1 - Purge all Neo4j and Cypher trademarks

diff --git a/cypher-shell/src/dist/geequel-shell b/cypher-shell/src/dist/geequel-shell
--- a/cypher-shell/src/dist/geequel-shell
+++ b/cypher-shell/src/dist/geequel-shell
@@ -69,12 +69,12 @@ _show_java_help() {
 build_classpath() {
   APP_HOME="$(cd "$(dirname "$0")" && pwd)"
   # First try in sub directory
-  JARPATH="$(find "${APP_HOME}" -name "cypher-shell.jar" )"
+  JARPATH="$(find "${APP_HOME}" -name "geequel-shell.jar" )"
 
-  # Then try installation directory (prefix/bin and prefix/share/cypher-shell/lib)
+  # Then try installation directory (prefix/bin and prefix/share/geequel-shell/lib)
   if [[ -z "${JARPATH}" ]]; then
-    APP_HOME="${APP_HOME}/../share/cypher-shell"
-    JARPATH="$(find "${APP_HOME}" -name "cypher-shell.jar" )"
+    APP_HOME="${APP_HOME}/../share/geequel-shell"
+    JARPATH="$(find "${APP_HOME}" -name "geequel-shell.jar" )"
   fi
 }
 
@@ -82,7 +82,7 @@ check_java
 build_classpath
 
 if [ -z "${JARPATH}" ]; then
-  echo "Unable to locate cypher-shell library files" >&2
+  echo "Unable to locate geequel-shell library files" >&2
   exit 1
 fi
 
